//
//  ListViewController.swift
//  HammerSystemsTest
//
//  Created by Михаил Кулагин on 24.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListDisplayLogic: AnyObject {
    func displayDrinks(viewModel: ListViewModel)
    func displayPizza(viewModel: ListViewModel)
    func displayCombo(viewModel: ListViewModel)
    func displayDesserts(viewModel: ListViewModel)
}

class ListViewController: UIViewController, ListDisplayLogic {
    var interactor: ListBusinessLogic?
    
    // MARK: Banners
    private let banners = [
        Category(id: 1, name: "", tagline: "", imageURL: ""),
        Category(id: 2, name: "", tagline: "", imageURL: ""),
        Category(id: 3, name: "", tagline: "", imageURL: ""),
        Category(id: 4, name: "", tagline: "", imageURL: "")
    ]
    
    // MARK: From Web
    private var drinks:   [Category] = []
    
    // MARK: From JSON Mocks
    private var pizza:    [Category] = []
    private var combo:    [Category] = []
    private var desserts: [Category] = []
    
    var dataSource: UICollectionViewDiffableDataSource<Section, Category>?
    var collectionView: UICollectionView!
    
    enum Section: Int, CaseIterable {
        case banners, drinks, pizza, combo, desserts
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        ListConfigurator.shared.configure(with: self)
        
        setupCollectionView()
        createDataSource()
        
        fetchDrinks()
        fetchPizza()
        fetchCombo()
        fetchDesserts()
        
        setupFakeCustomLeftBarButtonItem()
    }
    
// MARK: - Setup CollectionView
    private func setupCollectionView() {
        collectionView = UICollectionView(frame: view.bounds, collectionViewLayout: createCompositionalLayout())
        collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        collectionView.backgroundColor = .systemGray5
        view.addSubview(collectionView)
        
        collectionView.register(BannerCell.self, forCellWithReuseIdentifier: BannerCell.reuseId)
        collectionView.register(DrinkCell.self,   forCellWithReuseIdentifier: DrinkCell.reuseId)
        collectionView.register(PizzaCell.self,   forCellWithReuseIdentifier: PizzaCell.reuseId)
        collectionView.register(ComboCell.self,   forCellWithReuseIdentifier: ComboCell.reuseId)
        collectionView.register(DessertCell.self, forCellWithReuseIdentifier: DessertCell.reuseId)
    }
    
// MARK: - Reload data
    private func reloadData() {
        var snapshot = NSDiffableDataSourceSnapshot<Section, Category>()
        
        snapshot.appendSections([.banners, .drinks, .pizza, .combo, .desserts])
        
        snapshot.appendItems(banners, toSection: .banners)
        snapshot.appendItems(drinks, toSection: .drinks)
        snapshot.appendItems(pizza, toSection: .pizza)
        snapshot.appendItems(combo, toSection: .combo)
        snapshot.appendItems(desserts, toSection: .desserts)
        
        dataSource?.apply(snapshot, animatingDifferences: true)
    }
    
    private func setupFakeCustomLeftBarButtonItem() {
        let moscowLabel = UILabel()
        moscowLabel.text = "Moscow ∨"
        moscowLabel.font = .systemFont(ofSize: 18, weight: .medium)
        let customLeftBarButtonItem = UIBarButtonItem(customView: moscowLabel)
        navigationItem.leftBarButtonItem = customLeftBarButtonItem
    }
    
// MARK: - ViewController to Interactor
    func fetchDrinks() {
        interactor?.fetchDrinks()
    }
    
    func fetchPizza() {
        interactor?.fetchPizza()
    }
    
    func fetchCombo() {
        interactor?.fetchCombo()
    }
    
    func fetchDesserts() {
        interactor?.fetchDesserts()
    }
    
// MARK: - Display logic
    func displayDrinks(viewModel: ListViewModel) {
        drinks = viewModel.category
        reloadData()
    }
    
    func displayPizza(viewModel: ListViewModel) {
        pizza = viewModel.category
    }
    
    func displayCombo(viewModel: ListViewModel) {
        combo = viewModel.category
    }
    
    func displayDesserts(viewModel: ListViewModel) {
        desserts = viewModel.category
    }
    
} // ListViewController

// MARK: - Data Source
extension ListViewController {
    private func createDataSource() {
        dataSource = UICollectionViewDiffableDataSource<Section, Category>(collectionView: collectionView, cellProvider: { (collectionView, indexPath, category) -> UICollectionViewCell? in
            
            guard let section = Section(rawValue: indexPath.section) else { fatalError("Unknown section kind") }
            
            switch section {
            case .banners:
                let cell = collectionView.dequeueReusableCell(withReuseIdentifier: BannerCell.reuseId, for: indexPath) as! BannerCell
                cell.bannerImageView.image = UIImage(named: "banner1")
                return cell
            case .drinks:
                return self.configure(collectionView: collectionView, cellType: DrinkCell.self, with: category, for: indexPath)
            case .pizza:
                return self.configure(collectionView: collectionView, cellType: PizzaCell.self, with: category, for: indexPath)
            case .combo:
                return self.configure(collectionView: collectionView, cellType: ComboCell.self, with: category, for: indexPath)
            case .desserts:
                return self.configure(collectionView: collectionView, cellType: DessertCell.self, with: category, for: indexPath)
            }
        })
    }
}

// MARK: - Setup layout
extension ListViewController {
    private func createCompositionalLayout() -> UICollectionViewLayout {
        
        let layout = UICollectionViewCompositionalLayout { (senctionIndex, layoutEnvironment) -> NSCollectionLayoutSection? in
            
            guard let section = Section(rawValue: senctionIndex) else { fatalError("Unknown section kind") }
            
            switch section {
            case .banners:
                return self.createSectionForBanners()
            case .drinks:
                return self.createSection()
            case .pizza:
                return self.createSection()
            case .combo:
                return self.createSection()
            case .desserts:
                return self.createSection()
            }
        }
        
        let config = UICollectionViewCompositionalLayoutConfiguration()
        config.interSectionSpacing = 10
        layout.configuration = config
        return layout
    }
    
    private func createSection() -> NSCollectionLayoutSection {
        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1),
                                              heightDimension: .fractionalHeight(1))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        
        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1),
                                               heightDimension: .absolute(88))
        let group = NSCollectionLayoutGroup.vertical(layoutSize: groupSize, subitems: [item])
        
        let section = NSCollectionLayoutSection(group: group)
        section.interGroupSpacing = 1
        section.contentInsets = NSDirectionalEdgeInsets.init(top: 16, leading: 0, bottom: 0, trailing: 0)
        
        return section
    }
    
    private func createSectionForBanners() -> NSCollectionLayoutSection {
        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1),
                                              heightDimension: .fractionalHeight(1))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        
        let groupSize = NSCollectionLayoutSize(widthDimension: .absolute(264),
                                               heightDimension: .absolute(132))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitems: [item])
        
        let section = NSCollectionLayoutSection(group: group)
        section.interGroupSpacing = 10
        section.contentInsets = NSDirectionalEdgeInsets.init(top: 16, leading: 16, bottom: 0, trailing: 16)
        section.orthogonalScrollingBehavior = .continuous
        
        return section
    }
    
}

// MARK: - SwiftUI
import SwiftUI

struct ListVCProvider: PreviewProvider {
    static var previews: some View {
        ContainerView().edgesIgnoringSafeArea(.all)
    }
    
    struct ContainerView: UIViewControllerRepresentable {
        let mainTabBarController = MainTabBarController()
        func makeUIViewController(context: UIViewControllerRepresentableContext<ListVCProvider.ContainerView>) -> MainTabBarController {
            return mainTabBarController
        }
        
        func updateUIViewController(_ uiViewController: ListVCProvider.ContainerView.UIViewControllerType, context: UIViewControllerRepresentableContext<ListVCProvider.ContainerView>) {}
    }
}
