//
//  ListInteractor.swift
//  HammerSystemsTest
//
//  Created by Михаил Кулагин on 24.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBusinessLogic {
    func doSomething(request: ListRequest)
}

protocol ListDataStore {

}

class ListInteractor: ListBusinessLogic, ListDataStore {
    
    var presenter: ListPresentationLogic?
    var worker: ListWorker?
    
    // MARK: Do something
    
    func doSomething(request: ListRequest) {
        worker = ListWorker()
        worker?.doSomeWork()
        
        let response = ListResponse()
        presenter?.presentSomething(response: response)
    }
}
