//
//  ListModels.swift
//  HammerSystemsTest
//
//  Created by Михаил Кулагин on 24.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias ListRequest = List.Something.Request
typealias ListResponse = List.Something.Response
typealias ListViewModel = List.Something.ViewModel

enum List {
    // MARK: Use cases
    
    enum Something {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
}
