//
//  ListModels.swift
//  HammerSystemsTest
//
//  Created by Михаил Кулагин on 24.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit



typealias ListRequest = List.ShowCategories.Request
typealias ListResponse = List.ShowCategories.Response
typealias ListViewModel = List.ShowCategories.ViewModel

enum List {
    
    // MARK: Use cases
    enum ShowCategories {
        
        struct Request {
            
        }
        
        struct Response {
            let category: [Category]
        }
        
        struct ViewModel {
            let category: [Category]
        }
        
    }
}
