//
//  ListPresenter.swift
//  HammerSystemsTest
//
//  Created by Михаил Кулагин on 24.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
    func presentDrinks(response: ListResponse)
    func presentPizza(response: ListResponse)
    func presentCombo(response: ListResponse)
    func presentDesserts(response: ListResponse)
}

class ListPresenter: ListPresentationLogic {
    weak var viewController: ListDisplayLogic?
    
// MARK: - Presenter to ViewController
    
    func presentDrinks(response: ListResponse) {
        let drinksViewModel = ListViewModel(category: response.category)
        viewController?.displayDrinks(viewModel: drinksViewModel)
    }
    
    func presentPizza(response: ListResponse) {
        let pizzaViewModel = ListViewModel(category: response.category)
        viewController?.displayPizza(viewModel: pizzaViewModel)
    }
    
    func presentCombo(response: ListResponse) {
        let comboViewModel = ListViewModel(category: response.category)
        viewController?.displayCombo(viewModel: comboViewModel)
    }
    
    func presentDesserts(response: ListResponse) {
        let dessertsViewModel = ListViewModel(category: response.category)
        viewController?.displayDesserts(viewModel: dessertsViewModel)
    }
}
