//
//  ListViewController.swift
//  HammerSystemsTest
//
//  Created by Михаил Кулагин on 24.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListDisplayLogic: AnyObject {
    func displaySomething(viewModel: List.Something.ViewModel)
}

class ListViewController: UITableViewController, ListDisplayLogic {
        
    var interactor: ListBusinessLogic?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        ListConfigurator.shared.configure(with: self)
        doSomething()
    }
    
    // MARK: Do something
    
    func doSomething() {
        let request = ListRequest()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: ListViewModel) {

    }
    
}
